@baseUrl=http://localhost:8080/v1/patients

## 1. Save
### 1.1. Save with success
POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
    "name": "Fulano",
    "cpf": "548.030.450-03",
    "birthDate": "2000-01-01",
    "email": "fulano@mail.com",
    "phone": "(99) 9 9999-9999"
}

### 1.2. Save with validation fail
POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
    "name": "Fulano",
    "cpf": "111.222.333-44",
    "birthDate": "2000-01-01",
    "email": "fulano@mail.com",
    "phone": "(99) 9 9999-9999"
}

## 2. Edit
### 2.1. Edit with success
PUT {{baseUrl}}/46525b00-f8ec-4b70-873e-6bcfd5b7809e HTTP/1.1
content-type: application/json

{
    "name": "Fulano Edited",
    "cpf": "548.030.450-03",
    "birthDate": "2001-01-01",
    "email": "fulano@mail.com",
    "phone": "(99) 9 9999-9999"
}

### 2.2. Edit without data
PUT {{baseUrl}}/46525b00-f8ec-4b70-873e-6bcfd5b78091 HTTP/1.1
content-type: application/json

{
    "name": "Fulano Edited",
    "cpf": "548.030.450-03",
    "birthDate": "2001-01-01",
    "email": "fulano@mail.com",
    "phone": "(99) 9 9999-9999"
}

## 3. List
### 3.1. List all
GET {{baseUrl}}

### 3.2. List filtered data
GET {{baseUrl}}?name=ful&cpf=54

## 4. Find
### 4.1. Finding by id
GET {{baseUrl}}/46525b00-f8ec-4b70-873e-6bcfd5b7809e

### 4.2. Finding without data
GET {{baseUrl}}/46525b00-f8ec-4b70-873e-6bcfd5b78091

## 5. Delete
### 5.1. Deleting by id
DELETE {{baseUrl}}/46525b00-f8ec-4b70-873e-6bcfd5b7809e

### 5.2. Deleting without data
DELETE {{baseUrl}}/46525b00-f8ec-4b70-873e-6bcfd5b78091
